// <auto-generated />
using System;
using BeHealthBackend.DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeHealthBackend.Migrations
{
    [DbContext(typeof(BeHealthContext))]
    partial class BeHealthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Gdańsk",
                            PostalCode = "80-680",
                            Street = "ul. Nadwiślańska 112"
                        },
                        new
                        {
                            Id = 2,
                            City = "Gdynia",
                            PostalCode = "81-515",
                            Street = "ul. Kasztanowa 113"
                        },
                        new
                        {
                            Id = 3,
                            City = "Warszawa",
                            PostalCode = "01-401",
                            Street = " ul. Górczewska 82"
                        },
                        new
                        {
                            Id = 4,
                            City = "Warszawa",
                            PostalCode = "01-401",
                            Street = " ul. Akacjowa 22"
                        },
                        new
                        {
                            Id = 5,
                            City = "Łódź",
                            PostalCode = "91-503",
                            Street = "ul. Górna 82"
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Clinic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 5,
                            Description = "Zapraszamy",
                            Name = "Klinika Uśmiechu"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Description = "Lecz się u nas!",
                            Name = "Klinika Zdrowia"
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.ClinicDoctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "ClinicId");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicDoctor");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ClinicId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            ClinicId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            ClinicId = 2
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.ClinicPatient", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "ClinicId");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicPatient");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            ClinicId = 1
                        },
                        new
                        {
                            PatientId = 2,
                            ClinicId = 1
                        },
                        new
                        {
                            PatientId = 3,
                            ClinicId = 1
                        },
                        new
                        {
                            PatientId = 3,
                            ClinicId = 2
                        },
                        new
                        {
                            PatientId = 4,
                            ClinicId = 2
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Education")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Services")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Specialist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "EugeniuszKaminski@dayrep.com",
                            FirstName = "Eugeniusz",
                            LastName = "Kamiński",
                            PasswordHash = "azxsdcvfrewq",
                            PhoneNumber = "519439105",
                            Role = 1,
                            Specialist = "Oculist"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "SamKaczyński@dayrep.com",
                            FirstName = "Sam",
                            LastName = "Kaczyński",
                            PasswordHash = "azxsdbfymhsrewq",
                            PhoneNumber = "123432567",
                            Role = 1,
                            Specialist = "Cardiologist"
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.DoctorPatient", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "DoctorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorPatient");

                    b.HasData(
                        new
                        {
                            PatientId = 4,
                            DoctorId = 2
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "AdelajdaZielinska@teleworm.us",
                            FirstName = "Adelajda",
                            LastName = "Zielinska",
                            PasswordHash = "azxsdcvfrewqthb",
                            Pesel = "12345678901",
                            PhoneNumber = "692435107",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "WitoldKwiatkowski@armyspy.com",
                            FirstName = "Witołd",
                            LastName = "Kwiatkowski",
                            PasswordHash = "azxsdcvfrewq12",
                            Pesel = "12345678901",
                            PhoneNumber = "784251125",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Wolny23@armyspy.com",
                            FirstName = "Arni",
                            LastName = "Umbala",
                            PasswordHash = "azxsdcvfrewqfsa",
                            Pesel = "12345678901",
                            PhoneNumber = "879654239",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "JakubGrabowski@rhyta.com",
                            FirstName = "Jakub",
                            LastName = "Grabowski",
                            PasswordHash = "azxsdcvfavssw",
                            Pesel = "12345678901",
                            PhoneNumber = "531556254",
                            Role = 2
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            Duration = 65,
                            Name = "Konsultacja ortopedyczna + USG",
                            PatientId = 1,
                            VisitDate = new DateTime(2023, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 1,
                            Duration = 60,
                            Name = "Konsultacja reumatologiczna",
                            PatientId = 1,
                            VisitDate = new DateTime(2023, 1, 1, 12, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 1,
                            Duration = 45,
                            Name = "Terapia osoczem bogatym w czynniki wzrostu- PRP",
                            PatientId = 2,
                            VisitDate = new DateTime(2023, 1, 1, 13, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 1,
                            Duration = 60,
                            Name = "Terapia Orthokine",
                            PatientId = 3,
                            VisitDate = new DateTime(2023, 1, 2, 12, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Clinic", b =>
                {
                    b.HasOne("BeHealthBackend.DataAccess.Entities.Address", "Address")
                        .WithOne("Clinic")
                        .HasForeignKey("BeHealthBackend.DataAccess.Entities.Clinic", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.ClinicDoctor", b =>
                {
                    b.HasOne("BeHealthBackend.DataAccess.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BeHealthBackend.DataAccess.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.ClinicPatient", b =>
                {
                    b.HasOne("BeHealthBackend.DataAccess.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BeHealthBackend.DataAccess.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Doctor", b =>
                {
                    b.HasOne("BeHealthBackend.DataAccess.Entities.Address", "Address")
                        .WithOne("Doctor")
                        .HasForeignKey("BeHealthBackend.DataAccess.Entities.Doctor", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.DoctorPatient", b =>
                {
                    b.HasOne("BeHealthBackend.DataAccess.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BeHealthBackend.DataAccess.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Patient", b =>
                {
                    b.HasOne("BeHealthBackend.DataAccess.Entities.Address", "Address")
                        .WithOne("Patient")
                        .HasForeignKey("BeHealthBackend.DataAccess.Entities.Patient", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Visit", b =>
                {
                    b.HasOne("BeHealthBackend.DataAccess.Entities.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BeHealthBackend.DataAccess.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Address", b =>
                {
                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Doctor", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("BeHealthBackend.DataAccess.Entities.Patient", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
